services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blockchain_app
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
    networks:
      - "neurobackend_neurobackend_neuro-network"
    ports:
      - "3005:3000"

volumes:
  pgdata:

networks:
  neurobackend_neurobackend_neuro-network:
    external: true