version: "3.9"

services:
  db:
    image: postgres:17-alpine
    container_name: blockchain_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME:-blockchain_db}
    ports:
      - "7432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-blockchain_db}"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blockchain_app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      # Ensure app connects to the service name, not localhost
      DB_HOST: db
      DB_PORT: 5432
      PORT: 3000
      NODE_ENV: production
    ports:
      - "3000:3000"

volumes:
  pgdata:
