services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blockchain_app
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - "3005:3000"

volumes:
  pgdata: